### ISSUE TITLE
Bundeling the project causes  `Can't resolve 'MainActivity'`

### ISSUE THREAD

**Issue by Amathlai-softs** [NickIliev/NS-Issues-2018-II#1]
Hi @NickIliev .

Using the **exact**  `extendActivity' project : https://ufile.io/uhqs0 - with this command : 

```
tns run android --bundle --env.uglify --env.aot
```

Causes this error : 

![image](https://user-images.githubusercontent.com/2842123/41244369-87742958-6dad-11e8-96b0-bcb9b90c8241.png)

```
ERROR in Entry module not found: Error: Can't resolve 'MainActivity' in 'C:\nick\extendActivity\app'

ERROR in ./main.aot.ts
Module not found: Error: Can't resolve 'C:
ickextendActivityappMainActivity.android.js' in 'C:\nick\extendActivity\app'
 @ ./main.aot.ts 5:0-61
```

Notice , no slashed at `C:ickextendActivityappMainActivity.android.js`

Which is exactly what i'm facing [here](https://github.com/NativeScript/nativescript-dev-webpack/issues/559#issuecomment-396279840) .

Notice that the real PC path is : 

```
c:\nick\extendActivity\
```

![image](https://user-images.githubusercontent.com/2842123/41244483-d66ee58e-6dad-11e8-8189-eb0603bc1f33.png)

**Addditional info :** 

```
npm list -g --depth=0

C:\Users\royin\AppData\Roaming\npm
+-- nativescript@4.1.0
+-- npm@6.1.0
+-- typescript@2.8.3
`-- undefined@0.1.0
```

Additional info : 

```
sdkmanager --list
```
Result : https://pastebin.com/raw/0MnSEunL

**Comment by RoyiNamir** [comment]
Closing as it also happens/reported here https://github.com/NativeScript/nativescript-dev-webpack/issues/65

Thanks to  Nick for pointing that out. ( windows problem).
